#! /usr/bin/env python3

# Import the email modules we'll need
from email.parser import Parser
import argparse

# Get the filename from the command line
parser = argparse.ArgumentParser(description='Parse a MIME based Email')
parser.add_argument('filename', type=str, nargs=1,
                   help='The file containing the raw email')
args = vars(parser.parse_args())

# The message file contains the 'raw' email
messagefile = str(args['filename'][0])
with open(messagefile, 'r') as fp:
    headers = Parser().parse(fp)

print('To:      %s' % headers['to'])
print('From:    %s' % headers['from'])
print('Subject: %s' % headers['subject'])
print('Date:    %s' % headers['date'])

from dateutil import parser
#from datetime import datetime, timezone

completion = parser.parse(headers['date'])
#sentstr = 'Thursday, July 2, 2015 14:04 -0700'
#start = parser.parse(sentstr)

num = 1
body = ''
for part in headers.walk():
    print( '##########  Start Record: ' + str(num) + '  ###############' )
    type = part.get_content_maintype()
    print( '##########  Type: ' + type )
    fName = 'part-' + str(num)
    fp=open(fName, 'w')
    body = str(part.get_payload())
    fp.write(body)
    print( '##########  End   ' + str(num) + '  ###############' )
    fp.close()
    num += 1
    
print( '\n' )
print( 'Completion Time: %s' % completion )
#print( 'Start Time:      %s' % start )
#print( 'Elapsed Time:    %s' % (completion - start) )
#print( '######################## Start Body #################################' )
#print( body.replace('\n', '\\n').replace('\r','\\r'))
#print( '######################## End Body   #################################' )
print( '\n' )
