#! /usr/bin/env python3

# Import the email modules we'll need
from email.parser import Parser
import argparse

# Get the filename from the command line
parser = argparse.ArgumentParser(description='Parse a MIME based Email')
parser.add_argument('filename', type=str, nargs=1,
                   help='The file containing the raw email')
args = vars(parser.parse_args())

# The message file contains the 'raw' email
messagefile = str(args['filename'][0])
with open(messagefile, 'r') as fp:
    headers = Parser().parse(fp)

fp=open('subject','w')
fp.write(headers['subject'])
fp.close()
fp=open('from','w')
fp.write(headers['from'])
fp.close()

from dateutil import parser
#from datetime import datetime, timezone

completion = parser.parse(headers['date'])
#sentstr = 'Thursday, July 2, 2015 14:04 -0700'
#start = parser.parse(sentstr)

num = 1
body = ''
for part in headers.walk():
    type = part.get_content_maintype()
    if (type == 'text' ) :
        # Hope this is the 'ascii' version of the body
        body += '\n' + str(part.get_payload())
    num += 1
    if body :
        # Assume nothing else is needed
        break

fp=open('parsed-body','w')
fp.write(body)
fp.close()
